plugins {
    id 'java-library' // проект умеет компилировать java-код и создавать jar
    id 'io.qameta.allure' version '2.12.0' // подключает официальный плагин Allure для Gradle

    /* Именно он умеет:
    собирать результаты тестов в папку build/allure-results
    скачивать allure-commandline (для генерации красивого html-отчёта)
    добавлять задачи типа allureReport, allureServe */
}


// просто переменные
def allureVersion = "2.25.0",
    selenideVersion = "7.12.3"


allure {
    report {
        version.set(allureVersion) // какая версия Allure-отчёта будет генерироваться
    }

    adapter {                   // отвечает за появление папочки build/allure-results
        aspectjWeaver.set(true) //обработка аннотации @Step
        frameworks {
            junit5 {                         //название фреймворка
                adapterVersion.set(allureVersion) //версия интеграции фреймворка и Allure

            }
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(
            "com.codeborne:selenide:7.12.3",
            "com.github.javafaker:javafaker:1.0.2",
            "org.junit.jupiter:junit-jupiter:6.0.2",
            "org.assertj:assertj-core:3.27.6",
            "io.qameta.allure:allure-selenide:$allureVersion" // Selenide автоматически логирует действия в Allure

    )
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:6.0.2"
}



// Настройки для всех задач типа Test (то есть для gradle test, gradle simple_test и т.д.)
tasks.withType(Test) {
    useJUnitPlatform()

    testLogging {
        lifecycle {
            // когда тест начался
            //какие пропущены
            //какие упали
            //ошибки и обычный вывод (System.out / System.err)
            //Ошибки показывать коротко (не весь стек-трейс)
            events "started", "skipped", "failed", "standard_error", "standard_out"
            exceptionFormat "short"
        }
    }
}

// запускает только тесты с тегом @Tag("simple")
    task simple_test(type: Test) {
        useJUnitPlatform {
            includeTags("simple")
    }
}

// запускает только тесты с тегом @Tag("demoqa")
    task demoqa_test(type: Test) {
        useJUnitPlatform {
            includeTags("demoqa")
    }


    task remote_test(type: Test) {
        useJUnitPlatform {
            includeTags("remote")
        }
    }

    task property_test(type: Test) {
        useJUnitPlatform {
            includeTags("property")
        }
    }

    task hello_test(type: Test) {
        useJUnitPlatform {
            includeTags("hello")
        }
    }
        }